# Generated by Django 2.0.7 on 2018-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180805_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_stack_category',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Golang'), (3, 'Linux运维'), (4, 'Java')], verbose_name='主站分类'),
        ),
    ]
