# Generated by Django 2.0.7 on 2018-08-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180806_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='surfix',
            field=models.CharField(max_length=32, unique=True, verbose_name='后缀'),
        ),
    ]
