# Generated by Django 2.0.7 on 2018-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180812_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
    ]
