# Generated by Django 2.0.7 on 2018-08-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20180815_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='报障标题')),
                ('detail', models.TextField(verbose_name='故障描述')),
                ('ctime', models.CharField(max_length=32, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], verbose_name='障单状态')),
                ('solve_plan', models.TextField(verbose_name='解决方案')),
                ('stime', models.CharField(max_length=32, verbose_name='解决时间')),
                ('evaluate', models.IntegerField(choices=[(1, '活儿不行'), (2, '一般'), (3, '活儿很好')], verbose_name='评价')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='repository.User', verbose_name='提交者')),
            ],
        ),
    ]
