# Generated by Django 2.0.7 on 2018-08-17 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20180817_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='evaluate',
            field=models.IntegerField(blank=True, choices=[(1, '活儿不行'), (2, '一般'), (3, '活儿很好')], null=True, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.User'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='solve_plan',
            field=models.TextField(blank=True, null=True, verbose_name='解决方案'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='stime',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='解决时间'),
        ),
    ]
