# Generated by Django 2.1.1 on 2018-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20180826_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='repository.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='基本简介'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='博客主题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='博客标题'),
        ),
    ]
